workflows:
  ios-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            echo "Installing CocoaPods dependencies"
            pod install
          else
            echo "No Podfile found, skipping CocoaPods"
          fi

      - name: Build iOS app
        script: |
          echo "Building iOS application"
          xcodebuild -project DriverDetector.xcodeproj -scheme DriverDetector -configuration Release archive -archivePath build/app.xcarchive CODE_SIGNING_ALLOWED=NO

    artifacts:
      - build/*.xcarchive

