workflows:
  ios-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          if [ -f "Podfile" ]; then
            echo "Installing CocoaPods dependencies"
            pod install
          else
            echo "No Podfile found, skipping CocoaPods"
          fi

      - name: Build iOS app
        script: |
          echo "Building iOS application"
          # Adjust workspace/scheme as needed for your project
          if [ -f "*.xcworkspace" ]; then
            xcodebuild -workspace *.xcworkspace -scheme YourScheme -configuration Release archive -archivePath build/app.xcarchive CODE_SIGNING_ALLOWED=NO
          elif [ -f "*.xcodeproj" ]; then
            xcodebuild -project *.xcodeproj -scheme YourScheme -configuration Release archive -archivePath build/app.xcarchive CODE_SIGNING_ALLOWED=NO
          else
            echo "No Xcode project found"
            exit 1
          fi

    artifacts:
      - build/*.xcarchive

